library.jenkins-shared-library.version=main
project=roboshop
RUN_TESTS_DISPLAY_URL=http://jenkins.daws90s.shop:8080/job/ROBOSHOP/job/catalogue/job/main/3/display/redirect?page=tests
JENKINS_SERVER_COOKIE=durable-69c722b0a04e2addcebb3be28d8eba1a09fc80320f0823bdb7308360977dd415
GIT_PREVIOUS_SUCCESSFUL_COMMIT=08d6f652937067843c37203bbb08b59d462dec04
RUN_CHANGES_DISPLAY_URL=http://jenkins.daws90s.shop:8080/job/ROBOSHOP/job/catalogue/job/main/3/display/redirect?page=changes
HUDSON_HOME=/var/lib/jenkins
PWD=/var/lib/jenkins/workspace/ROBOSHOP_catalogue_main
LOGNAME=jenkins
BUILD_URL=http://jenkins.daws90s.shop:8080/job/ROBOSHOP/job/catalogue/job/main/3/
JOB_URL=http://jenkins.daws90s.shop:8080/job/ROBOSHOP/job/catalogue/job/main/
BUILD_NUMBER=3
SYSTEMD_EXEC_PID=1189
JENKINS_NODE_COOKIE=1f92ea2c-b642-40ba-a01a-e02e9150d1ed
BUILD_DISPLAY_NAME=#3
HOME=/var/lib/jenkins
LANG=C.UTF-8
JENKINS_URL=http://jenkins.daws90s.shop:8080/
JOB_BASE_NAME=main
JOB_NAME=ROBOSHOP/catalogue/main
INVOCATION_ID=aa928a20b616433d80868bd602629437
RUN_DISPLAY_URL=http://jenkins.daws90s.shop:8080/job/ROBOSHOP/job/catalogue/job/main/3/display/redirect
JOB_DISPLAY_URL=http://jenkins.daws90s.shop:8080/job/ROBOSHOP/job/catalogue/job/main/display/redirect
WORKSPACE=/var/lib/jenkins/workspace/ROBOSHOP_catalogue_main
GIT_PREVIOUS_COMMIT=08d6f652937067843c37203bbb08b59d462dec04
HUDSON_URL=http://jenkins.daws90s.shop:8080/
NODE_NAME=built-in
USER=jenkins
HUDSON_SERVER_COOKIE=f1021fc96471f42e
NOTIFY_SOCKET=/run/systemd/notify
GIT_URL=https://github.com/90s-org/catalogue.git
SHLVL=2
BUILD_TAG=jenkins-ROBOSHOP-catalogue-main-3
EXECUTOR_NUMBER=1
HUDSON_COOKIE=5637e8bd-e711-45aa-9639-de9376a3b2bf
JENKINS_HOME=/var/lib/jenkins
GIT_COMMIT=08d6f652937067843c37203bbb08b59d462dec04
NODE_LABELS=built-in
STAGE_NAME=Build
JOURNAL_STREAM=8:24497
WORKSPACE_TMP=/var/lib/jenkins/workspace/ROBOSHOP_catalogue_main@tmp
BRANCH_IS_PRIMARY=true
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin
RUN_ARTIFACTS_DISPLAY_URL=http://jenkins.daws90s.shop:8080/job/ROBOSHOP/job/catalogue/job/main/3/display/redirect?page=artifacts
CI=true
BRANCH_NAME=main
GIT_BRANCH=main
BUILD_ID=3
component=catalogue
_=/usr/bin/printenv